load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = [
        "lego.go",
        "lego_colors.go",
        "lego_elements.go",
        "lego_minifigs.go",
        "lego_part_categories.go",
        "lego_parts.go",
        "lego_sets.go",
        "lego_themes.go",
        "root.go",
        "sets.go",
        "user.go",
    ],
    importpath = "github.com/bu3/rebrickable-cli/cli/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_bu3_rebrickable_go//:rebrickable-go",
        "@com_github_spf13_cobra//:cobra",
    ],
)
